<pre class='metadata'>
Title: CSS Masonry (alt proposal)
Shortname: css-masonry
Level: 1
Status: w3c/UD
Group: CSSWG
Repository: tabatkins/specs
URL: http://tabatkins.github.io/specs/css-masonry/
Editor: Tab Atkins-Bittner, http://xanthir.com/contact
Abstract: An alternate syntax proposal for the Masonry feature currently defined in Grid 3.
Complain About: accidental-2119 yes, missing-example-ids yes
Markup Shorthands: markdown yes
</pre>

Introduction {#intro}
=====================

"Masonry" is the common name for a form of layout
that's somewhat "halfway" between Flexbox and Grid layout:
you pre-define some tracks in one axis
(either rows or columns),
and child elements flow into those tracks,
automatically distributing themselves across them
to keep the "heights" of the tracks as similar as possible.

The end result is similar to an auto-flowed Grid,
but "packed tighter",
rather than requiring the elements to line up in both rows <em>and</em> columns.
Alternately,
it's similar to a Flexbox,
except the "lines" are pre-defined
and the items automatically distribute themselves across them,
rather than filling one line at a time until it's full.

This proposal is intentionally just a sketch of the full spec;
for the most part, the final spec will closely resemble that of the Grid spec [[css-grid-1]],
so any "missing" parts should be assumed to be identical to Grid,
mutatis mutandi.

Masonry Containers {#masonry-model}
==================

Establishing Masonry Containers: the ''masonry'' and ''inline-masonry'' 'display' values {#masonry-containers}
----------------------------------------------------------------------------------------

	<pre class="propdef partial">
	Name: display
	New values: masonry | inline-masonry
	</pre>

	<dl dfn-type=value dfn-for=display>
		: <dfn>masonry</dfn>
		:: This value causes an element to generate a [=masonry container=] box
			that is [=block-level=] when placed in [=flow layout=].

		: <dfn>inline-masonry</dfn>
		:: This value causes an element to generate a [=masonry container=] box
			that is [=inline-level=] when placed in [=flow layout=].
	</dl>


Defining the Masonry Tracks {#masonry-definition}
=================

The 'masonry-tracks' property {#the-masonry-tracks}
-----------------------------

<pre class=propdef>
Name: masonry-tracks
Value: <<masonry-track-list>> | <<masonry-auto-track-list>>
</pre>

The 'masonry-tracks' property defines the <dfn>masonry tracks</dfn>
for a [=masonry container=]:
a set of rows or columns
that fill the <dfn>masonry rectangle</dfn>.

Similar to Flexbox, Masonry is defined in terms of a [=main axis=] and a [=cross axis=].
For "column" [=masonry containers=],
the [=main axis=] is the [=masonry container's=] [=block axis=],
and is the direction that [=masonry items=] are packed "tightly" in;
the [=cross axis=] is its [=inline axis=],
and is the direction that lines of items are stacked.
For "row" [=masonry containers=],
it's the opposite.

The [=masonry tracks=] are all the same length in the [=main axis=],
but can have potentially differing widths in the [=cross axis=],
determined by 'masonry-tracks'.

Similar to Grid, [=masonry tracks=] are pre-defined with specific "widths",
and are separated by numbered lines,
which can potentially correspond to gaps
defined by 'row-gap' or 'column-gap'.

<pre class=prod>
<dfn>&lt;masonry-track-list></dfn> = [ <<line-names>>? [ <<track-size>> | <<track-repeat>> ] ]+ <<line-names>>?

<dfn>&lt;masonry-auto-track-list></dfn> = <<line-names>>? <<auto-repeat>> <<line-names>>?
</pre>