<pre class='metadata'>
Title: CSS Masonry (alt proposal)
Shortname: css-masonry
Level: 1
Status: w3c/UD
Group: CSSWG
Work Status: exploring
Repository: tabatkins/specs
URL: http://tabatkins.github.io/specs/css-masonry/
Editor: Tab Atkins-Bittner, http://xanthir.com/contact
Abstract: An alternate syntax proposal for the Masonry feature currently defined in Grid 3.
Complain About: accidental-2119 yes, missing-example-ids yes
Markup Shorthands: markdown yes
</pre>

Introduction {#intro}
=====================

	"Masonry" is the common name for a form of layout
	that's somewhat "halfway" between Flexbox and Grid layout:
	you pre-define some tracks in one axis
	(either rows or columns),
	and child elements flow into those tracks,
	automatically distributing themselves across them
	to keep the "heights" of the tracks as similar as possible.

	The end result is similar to an auto-flowed Grid,
	but "packed tighter",
	rather than requiring the elements to line up in both rows <em>and</em> columns.
	Alternately,
	it's similar to a Flexbox,
	except the "lines" are pre-defined
	and the items automatically distribute themselves across them,
	rather than filling one line at a time until it's full.

	This proposal is intentionally just a sketch of the full spec;
	for the most part, the final spec will closely resemble that of the Grid spec [[css-grid-1]],
	so any "missing" parts should be assumed to be identical to Grid,
	mutatis mutandi.

Masonry Containers {#masonry-model}
==================

Establishing Masonry Containers: the ''masonry'' and ''inline-masonry'' 'display' values {#masonry-containers}
----------------------------------------------------------------------------------------

	<pre class="propdef partial">
	Name: display
	New values: masonry | inline-masonry
	</pre>

	<dl dfn-type=value dfn-for=display>
		: <dfn>masonry</dfn>
		:: This value causes an element to generate a [=masonry container=] box
			that is [=block-level=] when placed in [=flow layout=].

		: <dfn>inline-masonry</dfn>
		:: This value causes an element to generate a [=masonry container=] box
			that is [=inline-level=] when placed in [=flow layout=].
	</dl>


Defining the Masonry {#masonry-definition}
=================

	A <dfn export>masonry container</dfn> contains a <dfn export>masonry grid</dfn>:
	a set of one or more <dfn export>masonry tracks</dfn>,
	which <dfn export>masonry items</dfn> are flowed into.

	The direction that the [=masonry tracks=] extend
	is the [=masonry container's=] [=main axis=]
	(the [=block axis=] for [=column masonry containers=];
	the [=inline axis=] for [=row masonry containers=]d),
	and the perpendicular direction,
	which tracks are stacked in,
	is the [=cross axis=].



Defining Tracks: the 'masonry-template-tracks' property {#template-tracks}
-----------------------------

	<pre class=propdef>
	Name: masonry-template-tracks
	Value: <<masonry-track-list>> | <<masonry-auto-track-list>> | <<masonry-intrinsic-track-list>> | subgrid <<line-name-list>>?
	Initial: repeat(auto-areas, auto)
	Applies to: [=masonry containers=]
	Inherited: no
	Percentages: n/a
	Computed value: by computed value type per item in the [=computed track list=]
	Animation type: if list lengths match, by [=computed value=] type; otherwise, discrete
	</pre>

	The 'masonry-template-tracks' property defines,
	as a space-separated [=track list=],
	the [=line names=] and [=track sizing functions=] of the [=masonry=].

	<pre class=prod>
	<dfn>&lt;masonry-track-list></dfn> =
		[ <<line-names>>? <<masonry-track-component>> ]+ <<line-names>>?
	<dfn>&lt;masonry-track-component></dfn> =
		<<extrinsic-track-size>> | <<extrinsic-fixed-repeat>>
	<dfn>&lt;extrinsic-track-size></dfn> =
		<<extrinsic-breadth>> | minmax( <<fixed-breadth>>, <<extrinsic-breadth>> )
	<dfn>&lt;extrinsic-breadth></dfn> =
		<<length-percentage [0,∞]>> | <<flex [0,∞]>>
	<dfn>&lt;extrinsic-fixed-repeat></dfn> =
		repeat( <<integer [1, ∞]>>, [ <<line-names>>? <<extrinsic-track-size>> ]+ <<line-names>>? )

	<dfn>&lt;masonry-auto-track-list></dfn> =
		[ <<line-names>> | <<masonry-track-list>> ]?
		<<extrinsic-auto-repeat>>
		[ <<line-names>> | <<masonry-track-list>> ]?
	<dfn>&lt;extrinsic-auto-repeat></dfn> =
		repeat( [ auto-areas | auto-fill ] , [ <<line-names>>? <<extrinsic-track-size>> ]+ <<line-names>>? )

	<dfn>&lt;masonry-intrinsic-track-list></dfn> =
		<<line-names>>? <<masonry-intrinsic-repeat>> <<line-names>>?
	<dfn>&lt;masonry-intrinsic-repeat></dfn> =
		repeat( [ <<integer [1, ∞]>> | auto-areas | auto-fill ] , <<line-names>>? <<intrinsic-track-size>> <<line-names>>? )
	<dfn>&lt;intrinsic-track-size></dfn> = <<intrinsic-breadth>> | minmax( <<inflexible-breadth>>, <<intrinsic-breadth>> ) | fit-content( <<length-percentage [0, ∞]>> )
	<dfn>&lt;intrinsic-breadth></dfn> = auto | min-content | max-content
	</pre>

	<div class=note>
		The complex grammar above is much easier to understand in natural language.

		Your track list can be any combination of:
		* fixed sizes (lengths/percentages)
		* flexible sizes (''fr'' units)
		* ''minmax()'' of fixed/flexibles sizes
		* ''repeat()'' with integer repetitions and fixed/flexible sizes
		* at most one ''repeat()'' with ''auto-areas''/''auto-fill'' repetitions

		Alternately, it can be a single ''repeat()'' (with any repetition count)
		using *intrinsic* sizes, like ''masonry-template-tracks/auto'' or ''masonry-template-tracks/min-content''.

		Or as a third option, it can be a ''subgrid'' keyword,
		which takes tracks from its parent [=grid container=] or [=masonry container=]
		according to its span.
	</div>

	<div class=note>

		While similar to 'grid-template-columns'/'grid-template-rows',
		'masonry-template-tracks' has a slightly different set of allowed values.

		Grid can use:
		* any combination of fixed, flexible, or intrinsic tracks,
			either directy or in integer ''repeat()''
		* only fixed or flexible tracks in ''auto-fill''/''auto-fit'' ''repeat()''.

		While Masonry can use:
		* any combination of fixed or flexible tracks (but not intrinsic tracks),
			either directly, in integer ''repeat()'', or in ''auto-fill'' ''repeat()''
		* any single intrinsic track size in ''auto-areas''/''auto-fill'' ''repeat()''
	</div>

	The <dfn value for=masonry-template-tracks>subgrid</dfn> value
	indicates that the masonry will adopt the spanned portion
	of its [=parent grid=] or [=parent masonry=].


### Track Sizes ### {#track-sizes}

	<dl dfn-for=masonry-template-tracks>
		: <dfn><<length-percentage [0, ∞]>></dfn>
		:: A non-negative length of percentage, as defined by CSS Values.
			[[css-values-3]]

			<<percentage>> values are relative to
			the [=inner size|inner=] [=cross size=] of the [=masonry container=].
			If the size of the [=masonry container=] depends on the size of its tracks,
			the the <<percentage>> must be treated as the [=default masonry size=],
			for the purpose of calculating the intrinsic sizes of the [=masonry container=],
			and then resolve against that resulting [=masonry container=] size
			for the purpose of laying out the [=masonry=] and its items.

		: <dfn><<flex [0, ∞]>></dfn>
		:: A non-negative dimension with the unit ''fr''
			specifying the track's [=flex factor=].
			Each <<flex>>-sized track takes a share of the remaining space
			in proportion to its [=flex factor=].
			<span class=note>For example, given a track listing of ''1fr 2fr'',
			the tracks will take up 1/3 and 2/3 of the [=leftover space=], respectively.</span>

		: <dfn>minmax(<var>min</var>, <var>max</var>)</dfn>
		:: Defines a size range
			greater than or equal to |min|
			and less than or equal to |max|.
			If the |max| is less than the |min|,
			then the |max| will be floored by the |min|
			(essentially yielding ''minmax(|min|, |min|)''.)

			As a maximum, a <<flex>> value sets the track's [=flex factor=];
			it is invalid as a minimum.

		: <dfn>auto</dfn>
		:: As a <em>maximum</em>:
			represents the largest [=max-content contribution=]
			among all the [=masonry items=],
			[=corrected for spanning=];
			but unlike ''masonry-template-track/max-content'',
			allows expansion of the track
			by the 'align-content' and 'justify-content' properties.

			As a <em>minimum</em>:
			represents the largest [=minimum size=]
			among all the [=masonry items=],
			[=corrected for spanning=].
			(This initially is often, but not always,
			equal to a ''masonry-template-track/min-content'' minimum--
			see XXX.)

			When appearing outside a ''minmax()'' notation:
			equivalent to ''minmax(auto, auto)'',
			representin the range between the minimum and maximum described above.
			(This behaves similarly to ''minmax(min-content, max-content)''
			in the most basic cases,
			but with extra abilities.)

		: <dfn>max-content</dfn>
		:: Represents the largest [=max-content contribution=]
			among all the [=masonry items=],
			[=corrected for spanning=].

		: <dfn>min-content</dfn>
		:: Represents the largest [=min-content contribution=]
			among all the [=masonry items=],
			[=corrected for spanning=].

		: <dfn>fit-content( <<length-percentage>> )</dfn>
		:: ...
	</dl>

	<div algorithm>
		To <dfn export for=masonry>correct for spanning</dfn>,
		find the specified intrinsic size of the [=masonry item=],
		subtract the sizes of the gaps it crosses,
		then divide by its span.

		Note: For single-track items,
		[=correcting for spanning=] has no effect.
	</div>

	<div algorithm>
		The <dfn export for=masonry>default masonry size</dfn>
		is the size that a [=masonry track=] would be
		if the masonry had ''masonry-template-tracks: repeat(N, auto)'',
		where N is the number of tracks that the [=masonry container=] has.
	</div>

### Repeating Tracks: the ''repeat()'' notation ### {#repeat}

	There are two distinct syntaxes for ''repeat()'' in Masonry:

	* ''repeat( [ <<integer>> | auto-areas | auto-fill ], <extrinsic-track-size>+ )'',
		which allows you to specify one or more tracks to repeat,
		using <<length-percentage>>, <<flex>>, or ''minmax()'' of those.

	* ''repeat( [ <<integer>> | auto-areas | auto-fill ], <intrinsic-track-size> )'',
		which allows you to specify a *single* track to repeat,
		using the intrinsic sizes (''masonry-template-track/auto'', ''masonry-template-track/min-content'', ''masonry-template-track/max-content'', or ''masonry-template-track/minmax()'' of them).

	An <<integer>> repeat simply represents the same thing
	as repeating the tracks specified by the second argument.
	For example, ''repeat(2, 1em 300px)''
	is identical to writing ''1em 300px 1em 300px''.

	An ''auto-fill'' repeat represents repeating the second argument
	the largest whole number of times
	that wouldn't cause the [=masonry grid=]
	(including tracks not in the ''repeat()'', gaps, etc)
	to overflow the [=content box=] of the [=masonry container=]
	(minimum of one repetition).

	An ''auto-areas'' repeat depends on the value of 'masonry-template-areas':
	* if 'masonry-template-areas' is ''masonry-template-areas/none'',
		behaves as ''auto-fill''.
	* otherwise, represents enough repetitions of the second argument
		(with the final repetition possibly being only partial)
		to match the number of tracks
		specified by 'masonry-template-areas'.

	<div class=example>
		For example, given ''masonry-template-areas: "a a a b b";'',
		a ''repeat(auto-areas, 100px 20px)''
		is equivalent to specifying ''100px 20px 100px 20px 100px'':
		two whole repeats and one partial repeat,
		to match up with the five tracks specified by the areas.
	</div>



Named Areas: the 'masonry-template-areas' property {#masonry-template-areas-property}
--------------------------------------------------

	<pre class=propdef>
	Name: masonry-template-areas
	Value: none | <<string>>
	Initial: none
	Applies to: [=masonry containers=]
	Inherited: no
	Percentages: n/a
	Computed Value: the keyword ''masonry-template-values/none'' or a string
	Canonical Order: per grammar
	Animation type: discrete
	</pre>

	This property specifies <dfn export>named masonry areas</dfn>,
	which can be referenced from the [=masonry-placement properties=].

	Values have the following meanings:

	<dl dfn-type=value dfn-for=masonry-template-areas>
		: <dfn>none</dfn>
		:: Indicates no [=named masonry areas=] are defined by this property.

			Note: [=Named masonry areas=] can still be created implicitly,
			by manually naming lines like <css>foo-start</css> and <css>foo-end</css>
			to create a <css>foo</css> area between them.

		: <dfn><<string>></dfn>
		:: The string is parsed into a number of cells, as follows:

			1. Tokenize the string into a list of the following tokens,
				using longest-match semantics:

				* A sequence of [=ident code points=], representing a <dfn dfn>named cell token</dfn> with a name consisting of its code points.
				* A sequence of one or more "." (U+002E FULL STOP), representing a <dfn dfn>null cell token</dfn>.
				* A sequence of whitespace, representing nothing (does not produce a token).
				* A sequence of any other code points, representing a <dfn dfn>trash token</dfn>.

			2. * A [=null cell token=] represents an unnamed area in the [=masonry container=], covering one [=masonry track=].

				* A [=named cell token=] creates a [=named masonry area=] with the same name.
					Multiple adjacent [=named cell tokens=] with the same name
					instead create a single named area that spans the corresponding number of [=masonry tracks=].

				* A [=trash token=] is a syntax error, and makes the declaration invalid.

			If the string doesn't define at least one cell token,
			the declaration is invalid.
			If the string defines multiple named areas with the same name,
			the declaration is invalid.

			Defined areas give [=implicitly assigned line names|implicit-assigned names=]
			to [=grid lines=] in the [=masonry container=].
	</dl>


Track Direction: the 'masonry-direction' property {#masonry-direction}
-------------------------------------------------

	<pre class=propdef>
	Name: masonry-direction
	Value: row | column | row-reverse | column-reverse
	Initial: column
	Inherited: no
	Applies to: [=masonry containers=]
	Computed value: as specified
	Animation type: discrete
	</pre>

	The 'masonry-direction' property
	specifies how [=masonry items=] are placed
	in the [=masonry container=],
	by setting the direction of the [=masonry container's=] [=main axis=],
	and its [=main-start=] and [=main-end=] directions.

	<dl dfn-type=value dfn-for=masonry-direction>
		: <dfn>column</dfn>
		:: The [=masonry container's=] [=main axis=] is its [=block axis=],
			and its [=main-start=] direction is its [=block-start=].

		: <dfn>column-reverse</dfn>
		:: The [=masonry container's=] [=main axis=] is its [=block axis=],
			and its [=main-start=] direction is its [=block-end=].

		: <dfn>row</dfn>
		:: The [=masonry container's=] [=main axis=] is its [=inline axis=],
			and its [=main-start=] direction is its [=inline-start=].

		: <dfn>row-reverse</dfn>
		:: The [=masonry container's=] [=main axis=] is its [=inline axis=],
			and its [=main-start=] direction is its [=inline-end=].
	</dl>

	The [=masonry container's=] [=cross axis=]
	is perpendicular to its [=main axis=];
	its [=cross-start=] direction
	is determined by 'masonry-fill'.
	The [=main-end=] and [=cross-end=] directions
	are opposite the [=main-start=] and [=cross-start=] directions.

	A [=masonry container=] is a <dfn export>column masonry container</dfn>
	if its [=main axis=] is the [=block axis=],
	or a <dfn export>row masonry container</dfn>
	if its [=main axis=] is the [=inline axis=].




Masonry Definition Shorthand: the 'masonry' property {#masonry-template}
-----------------------------------------------------------

<pre class="propdef shorthand">
Name: masonry-template
Value: <<'masonry-template-areas'> || <<'masonry-template-tracks'>> || <<'masonry-direction'>>
</pre>

The 'masonry-template' shorthand sets
'masonry-template-areas',
'masonry-template-tracks',
and 'masonry-direction' at the same time.


Placing Grid Items {#placing}
==================

	<dfn property>masonry-track</dfn>,
	<dfn property>masonry-track-start</dfn>,
	<dfn property>masonry-track-end</dfn>,
	and <dfn property>masonry-area</dfn>,
	with the obvious definitions
	matching 'grid-row'/etc.

	Spans are clamped at layout time to the defined masonry tracks;
	there is no "implicit grid".



Handling Ties During Filling: the 'masonry-fill' property {#masonry-fill}
---------------------------------------------------------

	<pre class=propdef>
	Name: masonry-fill
	Value: <<length-percentage>> || reverse?
	Initial: 1em
	Percentages: relative to the [=main axis=] [=content box=] size of the [=masonry container=]
	Inherited: no
	Applies to: [=masonry containers=]
	Computed value: a computed length, and optionally a ''masonry-fill/reverse'' keyword
	Animation type: discrete
	</pre>

	[=Masonry containers=] are filled
	by placing each [=masonry item=]
	in whichever [=masonry track=] is currently the least filled.
	When multiple tracks are tied for least-filled,
	placing the items in order looks good.
	But if tracks are only <em>very slightly</em> different heights,
	it can look strange to have them not fill in order,
	as the height differences aren't perceived as <em>meaningfully</em> different.

	'masonry-fill' specifies what the threshold is
	for considering tracks to be "the same height"
	(causing them to fill in order),
	and what direction they fill in
	when their heights are tied in this way.

	<dl dfn-type=value dfn-for=masonry-fill>
		: <dfn><<length>></dfn>
		:: Specifies the <dfn dfn for=masonry>tie threshold</dfn>
			for the [=masonry container=].
			Placement positions are considered to be equally good ("ties")
			if they are within the specified distance
			from the shortest position.

			Note: The initial value is a "small" distance (''1em'')
			that is probably appropriate to represent "close enough".

		: <dfn>reverse</dfn>
		:: If ''reverse'' is **not** specified,
			the [=masonry container's=] [=cross-start=] direction
			is its [=inline-start=] or [=block-start=] direction
			(whichever is in its [=cross axis=]).
			<span class=note>(This means that ties are broken
			by filling from start to end.)</span>

			If ''reverse'' **is** specified,
			the [=cross-start=] direction
			is its [=inline-end=] or [=block-end=] direction, instead.
	</dl>

	Issue: Is ''1em'' the right default?

	Issue: Do we want a <css>dense</css> option,
	a la 'grid-auto-flow'?
	It's much more expensive in Masonry,
	as you have to lay out the element in every possible gap spot
	to see if it's short enough to fit;
	Grid gets to just juggle some integers.
	Leaving it out for now;
	we can add it later if needed.


Masonry Placement Algorithm {#placement-algo}
---------------------------

Masonry distributes its items as evenly as possible
among its tracks,
always choosing the least-filled track to place the next item into.

An important property that this distribution maintains
is that it always "moves forward" when there are ties:
If multiple tracks are tied for shortest,
it will still evenly distribute items to them one-by-one,
even if they <em>remain</em> tied after each item is placed
(because the item is zero height,
or the [=tie threshold=] is a large value).

<div class=algorithm>
	The following <dfn export>masonry placement algorithm</dfn>
	determines the position of all the [=masonry items=]
	in a [=masonry container=],
	distributing them across the [=masonry tracks=]
	according to whichever is the least-filled.

	Note: This algorithm refers to the "index" of tracks,
	and talks about indexes being "smaller" or "larger" than each other;
	this implies numbering them from the [=cross-start=] side
	to the [=cross-end=] side
	(and is thus dependent on 'masonry-fill').

	1. Generate anonymous masonry items.

	1. For each [=masonry track=],
		maintain a |fill height|,
		initially ''0px'' for all tracks.

	1. Let |placement cursor| be an index into the track list,
		initially pointing to the first track.

	1. For each [=masonry item=] |item| in [=order-modified document order=]:

		1. Let |chosen start track| be an index into the track list,
			initially unset.

		1. If |item| has a definite track position,
			set |chosen start track| to that position.

			Otherwise, [=choose a start track=],
			given |item|,
			the [=masonry tracks=] and their |fill height|s,
			the [=masonry container's=] [=tie threshold=],
			and |placement cursor|,
			and set |chosen start track| to the result.

		1. Let |spanned tracks| be the |chosen start track|
			plus following tracks according to |item|'s span.

		1. Lay out |item| into |spanned tracks|,
			as specified in [[#item-layout]].

			Let |item height| be the [=main size=] of |item| after layout.

		1. Let |max fill height| be the largest |fill height|
			among |spanned tracks|.

			Update all of |spanned tracks|'s |fill height|s
			to be |max fill height| + |item height|.

		1. If |item| did not have a definition track position initially,
			set |placement cursor| to the first track following |spanned tracks|;
			if there are no tracks following |spanned tracks|,
			set it to the first track.
			<span class=note>(Definite-position items don't update the cursor.)</span>
</div>

<div algorithm>
	Note: This algorithm chooses the track
	that would result in the item being placed as highly as possible.
	If there are ties, it chooses the earliest such track,
	<em>after</em> the most recently placed item if possible.

	To <dfn for=masonry>choose a start track</dfn> given:

	* a [=masonry item=] |item|
	* a set of [=masonry tracks=] |tracks| and their |fill height|s
	* a [=tie threshold=] |threshold|
	* a track index |placement cursor|

	1. Let |extra span| be |item|'s span - 1.

	1. Let |possible start tracks| be all but the last N |tracks|,
		where N is |extra span|.

	1. Let each item of |possible start tracks|
		have a |spanning fill height|,
		which is the largest |fill height|
		among the track itself and the next |extra span| tracks.

	1. Let |min fill height| be the smallest |spanning fill height| among |tracks|.

	1. Let |choosable tracks| be all the |possible start tracks|
		whose |spanning fill height|
		is within |threshold|
		of |min fill height|.

	1. If any of the |choosable tracks| indexes
		are equal or greater than |placement cursor|,
		remove any items from |choosable tracks|
		whose index is <em>smaller</em> than |placement cursor|.

	1. Return the item of |chooseable tracks| with the smallest index.
</div>





Alignment and Spacing {#alignment}
=====================

	Like Grid Layout [[css-grid-1]],
	the 'align-*' properties align in the [=masonry container's=] [=block axis=],
	and 'justify-*' in the [=inline axis=]
	(rather than being based on the [=main axis=] and [=cross axis=],
	like in Flexbox).

	For [=column masonry containers=]:

	: 'justify-content' on the [=masonry container=]
	:: The [=alignment subjects=] are the [=masonry tracks=].
		The [=alignment container=] is the [=masonry container's=] [=context box=].
	: 'align-content' on the [=masonry container=]
	:: The [=alignment subjects=] are
		runs of consecutive single-track [=masonry items=] in a given track
		between the start/end of the track or spanning items.
		The [=alignment container=] is the available space in the track
		between the two things bounding the run.
		(See <a href="https://github.com/w3c/csswg-drafts/issues/10275">Issue 10275</a>.)
	: 'justify-self' on the [=masonry items=]
	:: The [=alignment subject=] is the [=masonry item=].
		The [=alignment container=] is the available space
		in the [=masonry area=] the item is placed in.
	: 'align-self' on the [=masonry items=]
	:: No effect.

	For [=row masonry containers=],
	swap all the axises above.